/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pruebafinal;

import static com.sun.org.apache.xalan.internal.xsltc.compiler.util.Type.Int;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;


public class NewJFrame extends javax.swing.JFrame {

    DefaultTableModel mt = new DefaultTableModel(); 
    
    public NewJFrame() {
        initComponents();
        
        this.setTitle("Proyecto");
        this.setExtendedState(NORMAL);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        
        String [] ids = {"Nombre", "# Empleados", "Dirección", "Resiuos", "Impacto"};
        mt.setColumnIdentifiers(ids);
        TablaEmpresas.setModel(mt);
        
        TablaEmpresas.getSelectionModel().addListSelectionListener(new ListSelectionListener(){

            @Override
            public void valueChanged(ListSelectionEvent event) {
                if(!event.getValueIsAdjusting() && TablaEmpresas.getSelectedRow() != -1){
                    int fila = TablaEmpresas.getSelectedRow();
                
                    if(TablaEmpresas.getColumnCount() >= 5){
                        
                        Object nombre = TablaEmpresas.getValueAt(fila, 0);
                        Object cantEmpleados = TablaEmpresas.getValueAt(fila, 1);
                        Object direccion = TablaEmpresas.getValueAt(fila, 2);
                        Object residuos = TablaEmpresas.getValueAt(fila, 3);
                        Object impacto = TablaEmpresas.getValueAt(fila, 4);
                        
                        if(nombre != null && cantEmpleados != null && direccion != null && residuos != null && impacto != null){
                            TextNombre.setText(nombre.toString());
                            TextCantEmpleados.setText(cantEmpleados.toString());
                            TextDireccion.setText(direccion.toString());
                            CajaResiduos.setSelectedItem(residuos.toString());
                            
                        }else{
                            TextNombre.setText("");
                            TextCantEmpleados.setText("");
                            TextDireccion.setText("");
                            CajaResiduos.setSelectedItem("");
                        }
                    }else{
                        JOptionPane.showMessageDialog(null, "La tabla no tiene suficientes ncolumnas");
                    }
                }
                
            }
        
        });
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablaEmpresas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CajaResiduos = new javax.swing.JComboBox();
        TextNombre = new javax.swing.JTextField();
        TextCantEmpleados = new javax.swing.JTextField();
        TextDireccion = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        Archivos = new javax.swing.JMenu();
        menuItem_guardarInfo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TablaEmpresas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Titulo1", "Titulo2", "Titulo3", "Titulo4", "Titulo5"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TablaEmpresas);
        if (TablaEmpresas.getColumnModel().getColumnCount() > 0) {
            TablaEmpresas.getColumnModel().getColumn(1).setResizable(false);
        }

        jLabel1.setText("Nombre");

        jLabel2.setText("# Empleados");

        jLabel3.setText("Dirección");

        jLabel4.setText("Residuos");

        CajaResiduos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "No Contaminante", "Contaminante Sólido", "Contaminante Líquido", "Contaminante Gaseoso" }));

        TextNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextNombreActionPerformed(evt);
            }
        });

        TextCantEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextCantEmpleadosActionPerformed(evt);
            }
        });
        TextCantEmpleados.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextCantEmpleadosKeyTyped(evt);
            }
        });

        jButton1.setText("Nueva Empresa");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Listado de las Empresas con su impacto ambiental:");

        jButton2.setText("Borrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Actualizar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        Archivos.setText("Archivos");
        Archivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArchivosActionPerformed(evt);
            }
        });

        menuItem_guardarInfo.setText("Salvar Informacion");
        menuItem_guardarInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_guardarInfoActionPerformed(evt);
            }
        });
        Archivos.add(menuItem_guardarInfo);

        jMenuBar1.add(Archivos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1)))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TextCantEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TextDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(CajaResiduos, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(131, 131, 131)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(86, 86, 86))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 678, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(207, 207, 207)
                                .addComponent(jLabel5)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CajaResiduos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextCantEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextCantEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextCantEmpleadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextCantEmpleadosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if(TextNombre.getText().trim().isEmpty() || TextCantEmpleados.getText().trim().isEmpty() || TextDireccion.getText().trim().isEmpty() || CajaResiduos.getSelectedItem() == ""){
            JOptionPane.showMessageDialog(null, "Campo vacío", "Error", JOptionPane.WARNING_MESSAGE);
        }else{
            String nombre = String.valueOf(TextNombre.getText());
            int cantEmpleados = Integer.parseInt(this.TextCantEmpleados.getText());
            String direccion = String.valueOf(TextDireccion.getText());
            String residuo = String.valueOf(CajaResiduos.getSelectedItem());
            Double impacto = 0.0;
        
            if(residuo == "No impacto"){
                impacto = 0.0;
            }else if(residuo == "Contaminante Sólido"){
                impacto = 0.8;
            }else if(residuo == "Contaminante Gaseoso"){
                impacto = 1.7;
            }else if(residuo == "Contaminante Líquido"){
                impacto = 0.3;
            }
        
            impacto = cantEmpleados*impacto;
        
            mt.addRow(new Object[]{nombre,cantEmpleados,direccion,residuo,impacto});
            JOptionPane.showMessageDialog(null, "Empresa añadida correctamente", "Aviso", JOptionPane.INFORMATION_MESSAGE);

            TextNombre.setText("");
            TextCantEmpleados.setText("");
            TextDireccion.setText("");
            CajaResiduos.setSelectedItem("");
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        mt.removeRow(TablaEmpresas.getSelectedRow());
        
        JOptionPane.showMessageDialog(null, "Empresa borrada correctamente", "Aviso", JOptionPane.INFORMATION_MESSAGE);

        
        TextNombre.setText("");
        TextCantEmpleados.setText("");
        TextDireccion.setText("");
        CajaResiduos.setSelectedItem("");
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        String residuo = String.valueOf(CajaResiduos.getSelectedItem());
        int cantEmpleados = Integer.parseInt(this.TextCantEmpleados.getText());
        Double impacto = 0.0;
        
        if(residuo == "No impacto"){
            impacto = 0.0;
        }else if(residuo == "Contaminante Sólido"){
            impacto = 0.8;
        }else if(residuo == "Contaminante Gaseoso"){
            impacto = 1.7;
        }else if(residuo == "Contaminante Líquido"){
            impacto = 0.3;
        }
        
        impacto = cantEmpleados*impacto;
        
        mt.setValueAt(TextNombre.getText(), TablaEmpresas.getSelectedRow(), 0);
        mt.setValueAt(TextCantEmpleados.getText(), TablaEmpresas.getSelectedRow(), 1);
        mt.setValueAt(TextDireccion.getText(), TablaEmpresas.getSelectedRow(), 2);
        mt.setValueAt(CajaResiduos.getSelectedItem(), TablaEmpresas.getSelectedRow(), 3);
        mt.setValueAt((impacto), TablaEmpresas.getSelectedRow(), 4);

        JOptionPane.showMessageDialog(null, "Empresa actualizada correctamente", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        
        TextNombre.setText("");
        TextCantEmpleados.setText("");
        TextDireccion.setText("");
        CajaResiduos.setSelectedItem("");
        
        

        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void menuItem_guardarInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_guardarInfoActionPerformed
        
       String filePath = "D:\\Salva empresas.txt";
       File file = new File(filePath);
       
       try{
           FileWriter fw = new FileWriter(file);
           BufferedWriter bw = new BufferedWriter(fw);
           
           for(int i = 0; i < TablaEmpresas.getRowCount(); i++){
               for(int j = 0; j < TablaEmpresas.getColumnCount(); j++){
                   bw.write(TablaEmpresas.getValueAt(i, j).toString()+"; ");
               }
           }
           
           bw.close();
           fw.close();
           
           JOptionPane.showMessageDialog(null, "Información guardada correctamente", "Aviso", JOptionPane.INFORMATION_MESSAGE);
           
       }catch(IOException e){
        //Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE,null);
       }
        
    }//GEN-LAST:event_menuItem_guardarInfoActionPerformed

    private void ArchivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArchivosActionPerformed

    }//GEN-LAST:event_ArchivosActionPerformed

    private void TextCantEmpleadosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextCantEmpleadosKeyTyped
        char c = evt.getKeyChar();
        if(c < '0' || c > '9')evt.consume();
        
    }//GEN-LAST:event_TextCantEmpleadosKeyTyped

    private void TextNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNombreActionPerformed

        
    }//GEN-LAST:event_TextNombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Archivos;
    private javax.swing.JComboBox CajaResiduos;
    private javax.swing.JTable TablaEmpresas;
    private javax.swing.JTextField TextCantEmpleados;
    private javax.swing.JTextField TextDireccion;
    private javax.swing.JTextField TextNombre;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem menuItem_guardarInfo;
    // End of variables declaration//GEN-END:variables

   
    
}
